server:
  port: 80
spring:
  devtools:
    restart:
      poll-interval:
  application:
    name: cloud-order-server
  # consul注册中心
  cloud:
    consul:
      host: 192.168.31.100
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: 192.168.31.1
